### ISSUE TITLE
nicklen / userlen / channellen / topiclen

### ISSUE THREAD

**Issue by DanielOaks** [kaniini/mammon#36]
I should be able to look at this in the next few days, if someone else doesn't get to it before then.

Necessary because it stops various issues with people requesting stupidly large nicks and breaking clients, etc.

**Comment by Mikaela** [comment]
Partially relevant ZNC issue: https://github.com/znc/znc/issues/971

_(partially, because of no line length limit being intented)_

**Comment by kaniini** [comment]
The no line length limit is a local experiment to mammon, we are testing to see what clients would do if they receive too big of a line.  This shouldn't be interpreted to mean that clients should accept longer lines than 512 bytes, we are just doing an experiment.

Until and unless IRCv3-harmony changes the line length limit from 512 (note I say -harmony here because it's the RFC process), this is really just an experiment in undefined behaviour.  Whether we can do that in -harmony depends on how this experiment plays out.

**Comment by kaniini** [comment]
we should have configurable lengths on all the things (including maximum line limit), that will allow us to continue with our experiment while making sure that people using this in a more productionish environment (why would you do that yet i do not know) don't get crapflooded

**Comment by DanielOaks** [comment]
Yep, when those lines in the config are commented out it'll just ignore the length limits

**Comment by DanielOaks** [comment]
nicklen, channellen, topiclen, and linelen (maximum line length to/from clients) are now implemented with #37. userlen isn't yet.

I've seen other server implementations limit maximum hostname length as well (ie, if hostname is too long just fall back to using ip address instead), might be good to look into that and validating hostnames, to prevent stuff like https://github.com/inspircd/inspircd/issues/1033

**Comment by kaniini** [comment]
yes.  all of that is stuff we should do, but inspircd/inspircd#1033 shouldn't happen because our S2S protocol is going to be JSON-based

**Comment by DanielOaks** [comment]
All these length limits are now implemented.
