### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by MrHamel** [kaniini/mammon#50]
Just wow, you need another set of scripts for the IRC protocol on top of the main daemon. If this doesn't spell convoluted then I don't know what does.

It's like you take a perfectly good language and then make it fuck itself over. Besides, this will probably be like Anope 2 and never get used, so R.I.P. wasted time. Why not put the time into something useful, like, maintaining Atheme.

In before a CVE is made over the IRCv3 spec.

With Love,
Ryan ;)

**Comment by DanielOaks** [comment]
I'm sorry, what sort of scripts are you talking about? The `ext` modules?

We're splitting things up into self-contained modules where possible because we think it's cleaner to implement things that way. Each of the `ext` modules for instance contains all of how that feature works, instead of being scattered around the core in various places. If you think there's a nicer way to implement and structure these features, please feel free to submit PRs.

One of the goals of this is to provide a platform for easy prototyping of features, for instance to be able to write implementations of new IRCv3 specifications to help find issues with the specifications before they get released proper. That's something we helped do with the [metadata](https://github.com/ircv3/ircv3-specifications/pull/131) spec. In addition to that, providing a reference implementation for the proposed [register-and-verify](https://github.com/ircv3/ircv3-specifications/pull/152) specification.

Given that, I'd say we're already being used to fairly good effect and are likely to in the future as we get closer to an actual release at some point.

If you have any further issues, please feel free to let me know at [daniel@danieloaks.net](daniel@danieloaks.net).

Thanks for the feedback, it's much appreciated!

**Comment by kaniini** [comment]
![...](http://i3.kym-cdn.com/photos/images/newsfeed/000/326/657/087.jpg)

**Comment by kaniini** [comment]
> Just wow, you need another set of scripts for the IRC protocol on top of the main daemon. If this doesn't spell convoluted then I don't know what does.

To be clear, all of the other modern IRCds actually work this way too.  The core IRC implementation lives in modules, and the only thing in the ircd itself is just the state management.  It is true that mammon cleans up that mess a little.

> It's like you take a perfectly good language and then make it fuck itself over.

Actually using Python in this way is very correct, it is why `importlib` is provided.

> Besides, this will probably be like Anope 2 and never get used, so R.I.P. wasted time.

Actually there are quite a few people looking at it as a basis of their projects.  Mammon is mainly meant to be a research product, not a production software at this point in time.

> Why not put the time into something useful, like, maintaining Atheme.

This seems offtopic for Mammon's bug tracker, but a viable maintenance solution for Atheme is being worked on.  We have been trying to find a viable maintenance solution for Atheme for over 4 years, people did not heed our warnings, so we shut the project off.  There is approximately zero interest in further Atheme maintenance from most of the original developers.  It is unfortunate that it took shutting the project down to cause gears to move, but that is the situation.

> In before a CVE is made over the IRCv3 spec.

How exactly do you make a CVE over a spec?  CVEs cover software defects.
