### ISSUE TITLE
Implement IRC-style case equivalence

### ISSUE THREAD

**Issue by progval** [kaniini/mammon#76]
[RFC 1459](https://tools.ietf.org/html/rfc1459#section-2.2) and [RFC 2812](https://tools.ietf.org/html/rfc2812#section-2.2):

>   Because of IRC's scandanavian origin, the characters {}| are
>   considered to be the lower case equivalents of the characters []\,
>   respectively.

Charybdis and InspIRCd respect this, but not Mammon.

**Comment by DanielOaks** [comment]
That applies for `CASEMAPPING=rfc1459`.

We use the proposed `RPL_ISUPPORT` token value `CASEMAPPING=rfc3454`, described [here](http://rabbit.dereferenced.org/~nenolod/ircv3-harmony/id-wpitcock-ircv3-core.html#rfc.section.3.8.2.1.1), which we think is more suitable for software these days. This is because it defines a more extensive casemapping which works nicely with UTF-8.

This is not a bug, as we clearly define this with our `CASEMAPPING` `RPL_ISUPPORT` token. The same should go for Charybdis and InspIRCd, which should present something along the lines of: `CASEMAPPING=rfc1459` or similar describing their adherence to this.

**Comment by progval** [comment]
Fair enough
